"""Add TOTP fields

Revision ID: b59c60d58aa2
Revises: 865fe6b7b2b4
Create Date: 2026-01-13 01:44:00.953810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59c60d58aa2'
down_revision: Union[str, None] = '865fe6b7b2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    # SQLite requires server_default for NOT NULL columns
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # Removed unnecessary type alterations for SQLite
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
