"""create_study_uploads_table

Revision ID: c1a2b3c4d5e6
Revises: b59c60d58aa2
Create Date: 2026-01-13 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1a2b3c4d5e6'
down_revision = 'b59c60d58aa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_uploads',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('upload_id', sa.String(length=50), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('study_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_uploads_study_hash'), 'study_uploads', ['study_hash'], unique=False)
    op.create_index(op.f('ix_study_uploads_upload_id'), 'study_uploads', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_uploads_upload_id'), table_name='study_uploads')
    op.drop_index(op.f('ix_study_uploads_study_hash'), table_name='study_uploads')
    op.drop_table('study_uploads')
    # ### end Alembic commands ###
